module Arg {
    export interface CSSProperties {
        [prop:string]: any;
        display?: any;
        width?: any;
        height?: any;
        padding?: any;
        margin?: any;
        border?: any;
    }

    export interface Attrs {
        [key:string]: any;
        animation?: string;

        baseClassName?: any;
        classSet?: {[className: string]: any};
        self?: Atom<TreeItem>;

        children?: any;

        onmouseleave?:(ev:MouseEvent) => any;
        onbeforecut?:(ev:DragEvent) => any;
        onkeydown?:(ev:KeyboardEvent) => any;
        onmove?:(ev:MSEventObj) => any;
        onkeyup?:(ev:KeyboardEvent) => any;
        onreset?:(ev:Event) => any;
        onhelp?:(ev:Event) => any;
        ondragleave?:(ev:DragEvent) => any;
        onfocusin?:(ev:FocusEvent) => any;
        onseeked?:(ev:Event) => any;
        parentTextEdit?:Element;
        ondurationchange?:(ev:Event) => any;
        all?:HTMLCollection;
        onblur?:(ev:FocusEvent) => any;
        onemptied?:(ev:Event) => any;
        onseeking?:(ev:Event) => any;
        oncanplay?:(ev:Event) => any;
        ondeactivate?:(ev:UIEvent) => any;
        ondatasetchanged?:(ev:MSEventObj) => any;
        onrowsdelete?:(ev:MSEventObj) => any;
        onloadstart?:(ev:Event) => any;
        onlosecapture?:(ev:MSEventObj) => any;
        ondragenter?:(ev:DragEvent) => any;
        oncontrolselect?:(ev:MSEventObj) => any;
        onsubmit?:(ev:Event) => any;
        behaviorUrns?:MSBehaviorUrnsCollection;
        onchange?:(ev:Event) => any;
        onlayoutcomplete?:(ev:MSEventObj) => any;
        onbeforeactivate?:(ev:UIEvent) => any;
        oncanplaythrough?:(ev:Event) => any;
        onbeforeupdate?:(ev:MSEventObj) => any;
        onfilterchange?:(ev:MSEventObj) => any;
        ondatasetcomplete?:(ev:MSEventObj) => any;
        onsuspend?:(ev:Event) => any;
        onmouseenter?:(ev:MouseEvent) => any;
        onerrorupdate?:(ev:MSEventObj) => any;
        onmouseout?:(ev:MouseEvent) => any;
        parentElement?:HTMLElement;
        onmousewheel?:(ev:MouseWheelEvent) => any;
        onvolumechange?:(ev:Event) => any;
        oncellchange?:(ev:MSEventObj) => any;
        onrowexit?:(ev:MSEventObj) => any;
        onrowsinserted?:(ev:MSEventObj) => any;
        onpropertychange?:(ev:MSEventObj) => any;
        ondragend?:(ev:DragEvent) => any;
        onbeforepaste?:(ev:DragEvent) => any;
        ondragover?:(ev:DragEvent) => any;
        onmouseup?:(ev:MouseEvent) => any;
        ondragstart?:(ev:DragEvent) => any;
        onbeforecopy?:(ev:DragEvent) => any;
        ondrag?:(ev:DragEvent) => any;
        onmouseover?:(ev:MouseEvent) => any;
        onpause?:(ev:Event) => any;
        onmousedown?:(ev:MouseEvent) => any;
        onclick?:(ev:MouseEvent) => any;
        onwaiting?:(ev:Event) => any;
        onresizestart?:(ev:MSEventObj) => any;
        onpaste?:(ev:DragEvent) => any;
        onmoveend?:(ev:MSEventObj) => any;
        onstalled?:(ev:Event) => any;
        onmousemove?:(ev:MouseEvent) => any;
        onbeforeeditfocus?:(ev:MSEventObj) => any;
        onratechange?:(ev:Event) => any;
        onprogress?:(ev:any) => any;
        ondblclick?:(ev:MouseEvent) => any;
        oncontextmenu?:(ev:MouseEvent) => any;
        onloadedmetadata?:(ev:Event) => any;
        onafterupdate?:(ev:MSEventObj) => any;
        onerror?:(ev:Event) => any;
        onplay?:(ev:Event) => any;
        onresizeend?:(ev:MSEventObj) => any;
        onplaying?:(ev:Event) => any;
        onfocusout?:(ev:FocusEvent) => any;
        onabort?:(ev:UIEvent) => any;
        ondataavailable?:(ev:MSEventObj) => any;
        onreadystatechange?:(ev:Event) => any;
        onkeypress?:(ev:KeyboardEvent) => any;
        onloadeddata?:(ev:Event) => any;
        onbeforedeactivate?:(ev:UIEvent) => any;
        onactivate?:(ev:UIEvent) => any;
        onmovestart?:(ev:MSEventObj) => any;
        onselectstart?:(ev:Event) => any;
        onfocus?:(ev:FocusEvent) => any;
        ontimeupdate?:(ev:Event) => any;
        onresize?:(ev:UIEvent) => any;
        oncut?:(ev:DragEvent) => any;
        onselect?:(ev:UIEvent) => any;
        ondrop?:(ev:DragEvent) => any;
        oncopy?:(ev:DragEvent) => any;
        onended?:(ev:Event) => any;
        onscroll?:(ev:UIEvent) => any;
        onrowenter?:(ev:MSEventObj) => any;
        onload?:(ev:Event) => any;
        oninput?:(ev:Event) => any;


        accept?: any;
        acceptCharset?: any;
        accessKey?: any;
        action?: any;
        allowFullScreen?: any;
        allowTransparency?: any;
        alt?: any;
        async?: any;
        autoComplete?: any;
        autoFocus?: any;
        autoPlay?: any;
        cellPadding?: any;
        cellSpacing?: any;
        charSet?: any;
        checked?: any;
        classID?: any;
        className?: any;
        cols?: any;
        colSpan?: any;
        content?: any;
        contentEditable?: any;
        contextMenu?: any;
        controls?: any;
        coords?: any;
        crossOrigin?: any;
        data?: any;
        dateTime?: any;
        defer?: any;
        dir?: any;
        disabled?: any;
        download?: any;
        draggable?: any;
        encType?: any;
        form?: any;
        formNoValidate?: any;
        frameBorder?: any;
        height?: any;
        hidden?: any;
        href?: any;
        hrefLang?: any;
        htmlFor?: any;
        httpEquiv?: any;
        icon?: any;
        id?: any;
        label?: any;
        lang?: any;
        list?: any;
        loop?: any;
        manifest?: any;
        max?: any;
        maxLength?: any;
        media?: any;
        mediaGroup?: any;
        method?: any;
        min?: any;
        multiple?: any;
        muted?: any;
        name?: any;
        noValidate?: any;
        open?: any;
        pattern?: any;
        placeholder?: any;
        poster?: any;
        preload?: any;
        radioGroup?: any;
        readOnly?: any;
        rel?: any;
        required?: any;
        role?: any;
        rows?: any;
        rowSpan?: any;
        sandbox?: any;
        scope?: any;
        scrollLeft?: any;
        scrolling?: any;
        scrollTop?: any;
        seamless?: any;
        selected?: any;
        shape?: any;
        size?: any;
        sizes?: any;
        span?: any;
        spellCheck?: any;
        src?: any;
        srcDoc?: any;
        srcSet?: any;
        start?: any;
        step?: any;
        style?: CSSProperties;
        tabIndex?: any;
        target?: any;
        title?: any;
        type?: any;
        useMap?: any;
        value?: any;
        width?: any;
        wmode?: any;


        cx?: any;
        cy?: any;
        d?: any;
        dx?: any;
        dy?: any;
        fill?: any;
        fillOpacity?: any;
        fontFamily?: any;
        fontSize?: any;
        fx?: any;
        fy?: any;
        gradientTransform?: any;
        gradientUnits?: any;
        markerEnd?: any;
        markerMid?: any;
        markerStart?: any;
        offset?: any;
        opacity?: any;
        patternContentUnits?: any;
        patternUnits?: any;
        points?: any;
        preserveAspectRatio?: any;
        r?: any;
        rx?: any;
        ry?: any;
        spreadMethod?: any;
        stopColor?: any;
        stopOpacity?: any;
        stroke?: any;
        strokeDasharray?: any;
        strokeLinecap?: any;
        strokeOpacity?: any;
        strokeWidth?: any;
        textAnchor?: any;
        transform?: any;
        version?: any;
        viewBox?: any;
        x1?: any;
        x2?: any;
        x?: any;
        y1?: any;
        y2?: any;
        y?: any;
    }
}
